### ISSUE TITLE
Report is not a valid JUnit report

### ISSUE THREAD

**Issue by pouryafard75** [GaelGirodon/ci-badges-action#1]
Hello, I tried to use this project in my CI and get the following logs:

Load JUnit report '/home/runner/work/CI-test/CI-test/build/test-results/test/TEST-MyTest.xml'
Report is not a valid JUnit report
Load JUnit report '/home/runner/work/CI-test/CI-test/build/test-results/test/TEST-MyTest2.xml'
Report is not a valid JUnit report
Loaded 0 JUnit report(s)

TEST-MyTest2.xml is as follows:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="MyTest2" tests="1" skipped="0" failures="0" errors="0" timestamp="2024-04-18T02:45:37" hostname="PouryaMBP" time="0.001">
  <properties/>
  <testcase name="X()" classname="MyTest2" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>

```
I have checked the source code and it seems like the regex is trying to find **testsuites** but the junit test results has the keyword **testsuite** (s is missing at the end).

```
const report = await fs.readFile(r, { encoding: 'utf8' });
    const testsMatches = report
      .match(/(?<=<testsuites[^>]+tests=")[0-9]+(?=")/);
    const failedMatches = report
      .match(/(?<=<testsuites[^>]+failures=")[0-9]+(?=")/);
    if (testsMatches?.length !== 1 || failedMatches?.length !== 1) {
      core.info('Report is not a valid JUnit report');
      continue; // Invalid report file, trying the next one
    }
```

**Comment by GaelGirodon** [comment]
After some research, I found that JUnit XML test report files can contain:

- A root `<testsuites>` tag with multiple child `<testsuite>` tags (what I've seen the most during my browsing)
- A single root `<testsuite>` tag (maybe not so common but yet valid)

The current implementation is based on report files like this one:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Tests" time="9.891" tests="62" failures="0">
  <testsuite name="mdtodoc" timestamp="2024-04-18T19:12:28" tests="1" file="[...]" time="0.285" failures="0">
    <testcase name="CLI mdtodoc should fail without argument" time="0.284" classname="should fail without argument"></testcase>
  </testsuite>
  <testsuite name="mdtodoc -h/--help" timestamp="2024-04-18T19:12:28" tests="2" file="[...]" time="0.556" failures="0">
    <testcase name="CLI mdtodoc -h/--help should display help (-h)" time="0.285" classname="should display help (-h)"></testcase>
    <testcase name="CLI mdtodoc -h/--help should display help (--help)" time="0.271" classname="should display help (--help)"></testcase>
  </testsuite>
  [...]
</testsuites>
```

But having the sum of tests and failures in the root `<testsuites>` tag doesn't seem to be the most common and standard (e.g. the [`jest-junit`](https://www.npmjs.com/package/jest-junit) package generates a file with `testsuites`>`testsuite`>`testcase` tags hierarchy but doesn't output tests/failures sum in the root `<testsuites>` tag).

It may be more reliable to sum `tests`, `failures` and `errors` from each `<testsuite>` tag (whether there is only one at the root or multiple inside a root `<testsuites>` tag). That would make this loader more standard, thus supporting more report files, including yours (without breaking with mines).

Does it sound good to you?

P.S. Only the first valid report file (starting from the closest to the project root) is actually used to generate the badge. So make sure your test runner generates a single aggregated report file.
